version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
