name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install pytest  # Ensure pytest is installed

      - name: Run Tests
        run: pytest

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t nikhil0708/flask-app:latest .
          docker push nikhil0708/flask-app:latest
      - name: Deploy to EC2
        run: |
          ssh -i "javaapllication.pem" -o StrictHostKeyChecking=no ec2-user@44.197.187.50 << 'EOF'
          docker pull your-nikhil0708/flask-app:latest
          docker stop $(docker ps -q)
          docker run -d -p 8080:8080 nikhil0708/flask-app
          EOF

