name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install pytest  # Ensure pytest is installed

      - name: Run Tests
        run: pytest

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login "Nikhil0708" | docker login -u "Nikhil@1997" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t nikhil0708/flask-app:latest .
          docker push nikhil0708/flask-app:latest
